### ISSUE TITLE
有交流群嘛

### ISSUE THREAD

**Issue by listener-dong** [kakajun/qiankun-vite-test#2]
所以我想问，qiankun基站适合用vite嘛？大佬有交流群嘛

**Comment by kakajun** [comment]
![ed5c52bebe5b361303527ada9ec44c6e](https://user-images.githubusercontent.com/38216933/168705793-f4e38397-7842-413e-8a7f-fe1dead4af6b.jpg)

**Comment by kakajun** [comment]
qq交流群

**Comment by HollowWater** [comment]
您好，这个二维码过期了 能否在拉一下我

**Comment by kakajun** [comment]
> 

ka132300  备注qiankun
