### ISSUE TITLE
弱弱的问一下，依赖里的lerna是干嘛的？

### ISSUE THREAD

**Issue by Qwqw127** [kakajun/qiankun-vite-test#4]
![image](https://github.com/kakajun/qiankun-vite-test/assets/58459153/d1792e1e-28d2-4d12-89fe-cf11843c1479)

**Comment by kakajun** [comment]
做包管理的，不想用也可以去掉的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 上午10:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kakajun/qiankun-vite-test] 弱弱的问一下，依赖里的lerna是干嘛的？ (Issue #4)




 
image.png (view on web)
